default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Vagrant123#
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: tandaApp_dev

test:
  <<: *default
  database: tandaApp_test

production:
  <<: *default
  database: tandaApp